/**
 * @file Interactive setup CLI for Pocket CEP.
 *
 * Run with: npm run setup
 *
 * Guides a new developer through the .env.local configuration with live
 * validation at every step. Prompts are mode-aware (user_oauth asks for
 * Google OAuth creds; service_account walks through ADC) and API keys
 * are probed against the real upstream service before the script moves
 * on — so "setup finishes clean" is a real guarantee, not a vibe.
 *
 * Safe to re-run: existing .env.local values are loaded as defaults and
 * any keys we don't recognise are preserved unchanged on write.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join, resolve } from "node:path";
import { randomBytes } from "node:crypto";
import { select, input, password, confirm } from "@inquirer/prompts";
import { spawnSync } from "node:child_process";

import {
  probeAdcToken,
  probeAnthropicKey,
  probeGeminiKey,
  probeMcpServer,
} from "../src/lib/doctor-checks";
import { formatGcloudLoginCommand } from "../src/lib/google-scopes";
import { DEFAULT_MCP_URL } from "../src/lib/constants";
import { inferLlmProvider, type EnvMap } from "./setup-helpers";

const ENV_PATH = resolve(process.cwd(), ".env.local");

const DIM = "\x1b[2m";
const BOLD = "\x1b[1m";
const CYAN = "\x1b[36m";
const GREEN = "\x1b[32m";
const YELLOW = "\x1b[33m";
const RESET = "\x1b[0m";


/**
 * Parses an existing .env.local into a map so we can preserve unknown
 * keys and pre-fill known ones as prompt defaults. Mirrors the trivial
 * parser used by doctor.ts — no quoting, no variable expansion.
 */
function readExistingEnv(): EnvMap {
  if (!existsSync(ENV_PATH)) return {};
  const content = readFileSync(ENV_PATH, "utf-8");
  const env: EnvMap = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim();
    env[key] = value;
  }
  return env;
}

/**
 * Writes the env map back to disk as a predictable, human-editable file:
 * a header, then `KEY=value` lines grouped by section. Any keys in the
 * map we don't have a category for land under "Other" so re-running
 * setup never drops user additions on the floor.
 */
function writeEnv(env: EnvMap): void {
  const ordered: Array<[string, string[]]> = [
    ["Secrets", ["BETTER_AUTH_SECRET", "ANTHROPIC_API_KEY", "GOOGLE_AI_API_KEY"]],
    ["Google OAuth (user_oauth mode only)", ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"]],
    ["Mode", ["AUTH_MODE", "LLM_PROVIDER", "LLM_MODEL"]],
    ["URLs", ["BETTER_AUTH_URL", "MCP_SERVER_URL"]],
  ];

  const seen = new Set<string>();
  const lines: string[] = [
    "# Pocket CEP — .env.local (gitignored). Generated by `npm run setup`.",
    "# Holds your secrets and any per-developer overrides; wins over the",
    "# committed `.env` for any key set here. Re-running setup preserves",
    "# the values you set; hand-edits are safe.",
    "",
  ];

  for (const [section, keys] of ordered) {
    const present = keys.filter((k) => env[k] !== undefined && env[k] !== "");
    if (present.length === 0) continue;
    lines.push(`# ${section}`);
    for (const key of present) {
      lines.push(`${key}=${env[key]}`);
      seen.add(key);
    }
    lines.push("");
  }

  const unknown = Object.keys(env).filter((k) => !seen.has(k) && env[k] !== "");
  if (unknown.length > 0) {
    lines.push("# Other");
    for (const key of unknown) {
      lines.push(`${key}=${env[key]}`);
    }
    lines.push("");
  }

  writeFileSync(ENV_PATH, lines.join("\n"), { mode: 0o600 });
}

function banner(title: string, subtitle?: string) {
  console.log(`\n${BOLD}${title}${RESET}`);
  if (subtitle) console.log(`${DIM}${subtitle}${RESET}`);
}

function note(text: string) {
  console.log(`${DIM}${text}${RESET}`);
}

function checking(msg: string) {
  process.stdout.write(`  ${YELLOW}…${RESET} ${msg}…`);
}

function okClear(msg: string) {
  process.stdout.write(`\r  ${GREEN}✓${RESET} ${msg}${" ".repeat(20)}\n`);
}

function failClear(msg: string) {
  process.stdout.write(`\r  \x1b[31m✗${RESET} ${msg}${" ".repeat(20)}\n`);
}

/**
 * Wraps an inquirer `validate` callback that calls an upstream API so
 * the prompt's own red-text error line does the heavy lifting. Returns
 * `true` on success, an error string on failure (inquirer's contract).
 */
async function validateWithProbe(
  probe: () => Promise<{ ok: boolean; message: string }>,
  successMessage: string,
): Promise<true | string> {
  const result = await probe();
  return result.ok ? true : `${successMessage.replace("accepted", "rejected")} — ${result.message}`;
}

/**
 * Step 1: auth mode. We explain both flavors inline and use the
 * existing .env.local value as the default if re-running setup.
 */
async function chooseAuthMode(current: string | undefined) {
  banner("Step 1 · Authentication mode", "How does Pocket CEP talk to Google APIs?");
  return select<"service_account" | "user_oauth">({
    message: "Which auth mode?",
    default: current === "user_oauth" ? "user_oauth" : "service_account",
    choices: [
      {
        name: "service_account · ADC (recommended for local demos)",
        value: "service_account",
        description: "Uses `gcloud auth application-default login`. No user sign-in; shared identity.",
      },
      {
        name: "user_oauth · Google OAuth (per-user attribution)",
        value: "user_oauth",
        description: "Users sign in with Google. Their token is forwarded to the MCP server.",
      },
    ],
  });
}

/**
 * Step 3: LLM provider. Validation happens on the API-key step
 * downstream — we only pick the provider here. The default is
 * inferred from `.env.local` (explicit `LLM_PROVIDER` first, then
 * which API key happens to be set) so re-running setup with an
 * already-pasted key pre-selects the matching provider instead of
 * always landing on Claude.
 */
async function chooseLlmProvider(existing: EnvMap) {
  banner("Step 3 · LLM provider", "Which model powers the chat agent?");
  const inferred = inferLlmProvider(existing);
  if (inferred.reason) note(inferred.reason);
  return select<"claude" | "gemini">({
    message: "Which provider?",
    default: inferred.value,
    choices: [
      {
        name: "claude · Anthropic Claude (via @ai-sdk/anthropic)",
        value: "claude",
        description: "Requires an ANTHROPIC_API_KEY from https://console.anthropic.com/",
      },
      {
        name: "gemini · Google Generative AI (via @ai-sdk/google)",
        value: "gemini",
        description: "Requires a GOOGLE_AI_API_KEY from https://aistudio.google.com/apikey",
      },
    ],
  });
}

/**
 * Step 2: BETTER_AUTH_SECRET. Comes right after auth mode so the auth
 * setup stays grouped (the LLM provider+key pair flows next as a
 * single unit). If the current value looks unsafe (missing or the
 * placeholder from .env.local.example), we offer to generate a fresh
 * one. Otherwise we leave it untouched.
 */
async function chooseAuthSecret(current: string | undefined): Promise<string> {
  banner("Step 2 · BetterAuth signing secret", "Signs the session cookie. Treat it like a password.");

  const placeholder = "please-change-me-to-a-real-secret";
  const hasReal = current && current !== placeholder && current.length >= 32;

  if (hasReal) {
    const keep = await confirm({
      message: "An existing BETTER_AUTH_SECRET looks valid. Keep it?",
      default: true,
    });
    if (keep) return current;
  }

  const generate = await confirm({
    message: "Generate a cryptographically random 32-byte secret now?",
    default: true,
  });

  if (generate) {
    const secret = randomBytes(32).toString("base64");
    console.log(`  ${GREEN}✓${RESET} Generated a new 32-byte secret.`);
    return secret;
  }

  return password({
    message: "Paste your own BETTER_AUTH_SECRET:",
    mask: "•",
    validate: (v) => (v.trim().length >= 16 ? true : "Use at least 16 characters"),
  });
}

/**
 * If an existing key is present, probe it first and offer to keep it
 * so we don't ask the user to re-paste a working secret. Returns the
 * kept value or `null` to signal "prompt for a new one".
 */
async function tryKeepExistingKey(
  label: string,
  current: string | undefined,
  probe: (value: string) => Promise<{ ok: boolean; message: string }>,
): Promise<string | null> {
  if (!current) return null;
  checking(`Probing existing ${label}`);
  const result = await probe(current);
  if (!result.ok) {
    failClear(`Existing ${label} was rejected — you'll need to paste a new one`);
    return null;
  }
  okClear(`Existing ${label} is valid`);
  const keep = await confirm({ message: `Keep the existing ${label}?`, default: true });
  return keep ? current : null;
}

/**
 * Step 4a: Anthropic key — masked input, validated by the same
 * /v1/messages probe doctor uses. If the key is wrong we re-prompt;
 * we never move on with a bad key.
 */
async function promptAnthropicKey(current: string | undefined) {
  banner(
    "Step 4 · ANTHROPIC_API_KEY",
    "We'll probe https://api.anthropic.com/v1/messages to confirm it works.",
  );
  note("Get one at https://console.anthropic.com/ → Settings → API Keys");

  const kept = await tryKeepExistingKey("Anthropic key", current, probeAnthropicKey);
  if (kept) return kept;

  return password({
    message: "Paste your Anthropic API key:",
    mask: "•",
    validate: async (value) => {
      const trimmed = value.trim();
      if (!trimmed) return "Key is required";
      if (!trimmed.startsWith("sk-ant-")) {
        return "Anthropic keys start with `sk-ant-` — double-check the value";
      }
      return validateWithProbe(() => probeAnthropicKey(trimmed), "Key accepted");
    },
  });
}

/**
 * Step 4b: Google AI key — validated by listing models on
 * generativelanguage.googleapis.com.
 */
async function promptGeminiKey(current: string | undefined) {
  banner(
    "Step 4 · GOOGLE_AI_API_KEY",
    "We'll probe generativelanguage.googleapis.com/v1beta/models to confirm it works.",
  );
  note("Get one at https://aistudio.google.com/apikey");

  const kept = await tryKeepExistingKey("Google AI key", current, probeGeminiKey);
  if (kept) return kept;

  return password({
    message: "Paste your Google AI API key:",
    mask: "•",
    validate: async (value) => {
      const trimmed = value.trim();
      if (!trimmed) return "Key is required";
      return validateWithProbe(() => probeGeminiKey(trimmed), "Key accepted");
    },
  });
}

const GOOGLE_CLIENT_ID_RE = /^\d+-\w+\.apps\.googleusercontent\.com$/;

/**
 * Step 5 (user_oauth mode): Google OAuth client credentials. The
 * client ID format is strict, so we validate it with the same regex
 * the Zod env schema uses — catches paste errors here rather than as
 * a cryptic OAuth error at runtime. Mutually exclusive with the
 * service_account-mode `walkAdcSetup` below — the user only ever
 * sees one of them per setup run.
 */
async function promptGoogleOAuth(current: EnvMap) {
  banner(
    "Step 5 · Google OAuth client",
    "console.cloud.google.com → APIs & Services → Credentials",
  );
  note(
    "Add this redirect URI to your OAuth client:\n   http://localhost:3000/api/auth/callback/google",
  );

  const clientId = await input({
    message: "GOOGLE_CLIENT_ID:",
    default: current.GOOGLE_CLIENT_ID || undefined,
    validate: (v) => {
      const trimmed = v.trim();
      if (!trimmed) return "Client ID is required";
      return GOOGLE_CLIENT_ID_RE.test(trimmed)
        ? true
        : "Expected format: 123456789-abc.apps.googleusercontent.com";
    },
  });

  const clientSecret = await password({
    message: "GOOGLE_CLIENT_SECRET:",
    mask: "•",
    validate: (v) => (v.trim().length > 0 ? true : "Client secret is required"),
  });

  return { clientId: clientId.trim(), clientSecret: clientSecret.trim() };
}

/**
 * Returns true if the `gcloud` CLI is on PATH. ADC depends on it, so we
 * preflight before the ADC probe to give a clearer error when it's
 * missing entirely (the probe's "no credentials" message is confusing
 * if the real cause is "gcloud isn't installed yet").
 */
function isGcloudInstalled(): boolean {
  return spawnSync("gcloud", ["--version"], { stdio: "ignore" }).status === 0;
}

/**
 * Prints platform-appropriate gcloud install hints. Extracted so both
 * the "not installed" branch and the "still not installed after
 * re-check" branch render the same guidance.
 */
function printGcloudInstallHints(): void {
  console.log(`${DIM}The Google Cloud CLI is required for service-account mode —${RESET}`);
  console.log(`${DIM}Pocket CEP uses your Application Default Credentials.${RESET}`);
  console.log(`${DIM}Install it in another terminal, then come back:${RESET}\n`);

  if (process.platform === "darwin") {
    console.log(`  ${CYAN}brew install --cask google-cloud-sdk${RESET}`);
    console.log(`  ${DIM}or see https://cloud.google.com/sdk/docs/install-sdk${RESET}`);
  } else if (process.platform === "linux") {
    console.log(`  ${CYAN}https://cloud.google.com/sdk/docs/install-sdk#linux${RESET}`);
  } else if (process.platform === "win32") {
    console.log(`  ${CYAN}https://cloud.google.com/sdk/docs/install-sdk#windows${RESET}`);
  } else {
    console.log(`  ${CYAN}https://cloud.google.com/sdk/docs/install-sdk${RESET}`);
  }
  console.log();
  console.log(`${DIM}Tip: open a new shell after installing so PATH updates take effect.${RESET}\n`);
}

/**
 * Loops on "re-check or skip" until gcloud is installed or the user
 * chooses to defer. Returns true when gcloud is ready, false when the
 * user opted to skip ADC entirely.
 */
async function ensureGcloudInstalled(): Promise<boolean> {
  checking("Checking for `gcloud`");
  if (isGcloudInstalled()) {
    okClear("`gcloud` is installed");
    return true;
  }
  failClear("`gcloud` is not installed");

  for (;;) {
    printGcloudInstallHints();
    const next = await select<"recheck" | "skip">({
      message: "When you're ready:",
      default: "recheck",
      choices: [
        {
          name: "I've installed gcloud — re-check now",
          value: "recheck",
          description: "Verifies `gcloud --version` succeeds, then continues with ADC.",
        },
        {
          name: "Skip ADC for now",
          value: "skip",
          description: "Finish writing .env.local; run `npm run doctor` to verify later.",
        },
      ],
    });

    if (next === "skip") {
      note("Skipping ADC. After installing gcloud, run:");
      console.log(`  ${CYAN}gcloud auth application-default login${RESET}`);
      console.log(`  ${CYAN}npm run doctor${RESET}\n`);
      return false;
    }

    if (isGcloudInstalled()) {
      console.log(`  ${GREEN}✓${RESET} \`gcloud\` is installed\n`);
      return true;
    }
    console.log(`  \x1b[31m✗${RESET} Still not found. Open a new shell to refresh PATH.\n`);
  }
}

/**
 * Loops on "re-check or skip" until the ADC token exchange succeeds
 * or the user opts out. Assumes gcloud is already installed. Returns
 * true on a successful login (so the caller can chain quota-project
 * setup) or false on skip.
 */
async function ensureAdcLogin(): Promise<boolean> {
  for (;;) {
    checking("Checking Google ADC");
    const result = await probeAdcToken();
    if (result.ok) {
      okClear("ADC is configured and working");
      return true;
    }
    failClear(`ADC not ready — ${result.message}`);

    console.log(`${DIM}Pocket CEP needs a Workspace admin's ADC to call Chrome${RESET}`);
    console.log(`${DIM}Management, Admin SDK Directory + Reports, Cloud Identity,${RESET}`);
    console.log(`${DIM}and Licensing APIs. Run this in another terminal — paste${RESET}`);
    console.log(`${DIM}as a single line:${RESET}\n`);
    console.log(`  ${CYAN}${formatGcloudLoginCommand()}${RESET}\n`);
    console.log(
      `${DIM}Setup will help pin a quota project once login succeeds.${RESET}\n`,
    );

    const next = await select<"recheck" | "skip">({
      message: "When you're ready:",
      default: "recheck",
      choices: [
        {
          name: "I've logged in — re-check now",
          value: "recheck",
          description: "Verifies the token exchange succeeds.",
        },
        {
          name: "Skip for now",
          value: "skip",
          description: "`npm run doctor` will verify once you've logged in.",
        },
      ],
    });

    if (next === "skip") {
      note("Skipping ADC check. Run `npm run doctor` after logging in to verify.");
      return false;
    }
  }
}

/**
 * Reads the quota_project_id from the ADC credentials file directly
 * (uncached, sync) so a quota project freshly written by gcloud is
 * visible immediately. Returns null when the file is missing, the
 * field is absent, or the JSON is malformed.
 */
function readAdcQuotaProject(): string | null {
  try {
    const credPath = join(homedir(), ".config", "gcloud", "application_default_credentials.json");
    if (!existsSync(credPath)) return null;
    const raw: unknown = JSON.parse(readFileSync(credPath, "utf-8"));
    if (raw && typeof raw === "object" && "quota_project_id" in raw) {
      const value = (raw as { quota_project_id?: unknown }).quota_project_id;
      return typeof value === "string" && value.length > 0 ? value : null;
    }
    return null;
  } catch {
    return null;
  }
}

/**
 * Returns the project the user already has configured as their gcloud
 * default (`gcloud config get-value project`). Used as the pre-filled
 * answer for the quota-project prompt — covers the 99% case where
 * someone already has a working gcloud config and just wants to pin
 * the same project for ADC. Returns null if the value is `(unset)`,
 * gcloud is missing, or any other failure.
 */
function detectDefaultGcloudProject(): string | null {
  const result = spawnSync(
    "gcloud",
    ["config", "get-value", "project", "--quiet"],
    { encoding: "utf-8" },
  );
  if (result.status !== 0) return null;
  const value = result.stdout.trim();
  if (!value || value === "(unset)") return null;
  return value;
}

/**
 * Project IDs: 6-30 chars, lowercase letters/digits/hyphens, must
 * start with a letter. Caught here as a paste-error guard before the
 * gcloud subprocess call.
 */
const PROJECT_ID_RE = /^[a-z][a-z0-9-]{4,28}[a-z0-9]$/;

/**
 * Pins a quota project on the user's ADC credentials. Avoids
 * `gcloud projects list` because organisations frequently have
 * 100K+ projects and listing them all is slow and useless as a
 * picker. Instead we:
 *
 *   1. Read any existing quota_project_id from the ADC JSON. If set,
 *      just confirm it.
 *   2. Otherwise probe `gcloud config get-value project` for a
 *      sensible default.
 *   3. Prompt the user with that default pre-filled, plus inline
 *      help on how to find a project ID if they don't have one.
 *   4. Run `gcloud auth application-default set-quota-project` for
 *      them. Falls back to a printed manual command on any failure.
 */
async function ensureQuotaProject(): Promise<void> {
  const existing = readAdcQuotaProject();
  if (existing) {
    console.log(`  ${GREEN}✓${RESET} ADC quota project already set: ${CYAN}${existing}${RESET}\n`);
    return;
  }

  console.log(`${DIM}ADC has no quota project pinned yet. Pocket CEP needs one${RESET}`);
  console.log(`${DIM}so Workspace API calls bill and rate-limit against your project.${RESET}\n`);

  const detected = detectDefaultGcloudProject();
  if (detected) {
    console.log(
      `${DIM}Your gcloud config has \`project=${detected}\` — pre-filled as the default.${RESET}\n`,
    );
  } else {
    console.log(`${DIM}If you don't know the project ID:${RESET}`);
    console.log(`  ${DIM}• \`gcloud config get-value project\` shows your gcloud default${RESET}`);
    console.log(
      `  ${DIM}• console.cloud.google.com → project picker (top of page)${RESET}\n`,
    );
  }

  // Loop until set-quota-project succeeds or the user opts out.
  // gcloud rejects IDs the user has no access to even when the syntax
  // is valid; the regex can't catch that, so retry-with-a-different-ID
  // is the natural recovery path.
  let suggestedDefault = detected ?? undefined;
  for (;;) {
    const projectId = await input({
      message: "Project ID for ADC quota:",
      default: suggestedDefault,
      validate: (v) => {
        const trimmed = v.trim();
        if (!trimmed) return "Project ID is required";
        if (!PROJECT_ID_RE.test(trimmed)) {
          return "Project IDs are 6-30 chars, lowercase letters/digits/hyphens, starting with a letter";
        }
        return true;
      },
    });

    const trimmed = projectId.trim();
    checking(`Setting quota project to ${trimmed}`);
    const set = spawnSync(
      "gcloud",
      ["auth", "application-default", "set-quota-project", trimmed],
      { stdio: "ignore" },
    );
    if (set.status === 0) {
      okClear(`Quota project set to ${trimmed}`);
      return;
    }
    failClear(`\`gcloud\` rejected ${trimmed} — wrong ID, or no access?`);

    const next = await select<"retry" | "skip">({
      message: "What next?",
      default: "retry",
      choices: [
        { name: "Try a different project ID", value: "retry" },
        {
          name: "Skip — set it manually later",
          value: "skip",
          description: "Run `gcloud auth application-default set-quota-project <id>` yourself.",
        },
      ],
    });

    if (next === "skip") {
      console.log(`${DIM}Run manually once you have the right project ID:${RESET}`);
      console.log(
        `  ${CYAN}gcloud auth application-default set-quota-project YOUR_PROJECT_ID${RESET}\n`,
      );
      return;
    }
    // Drop the rejected ID as the default so the user re-enters fresh.
    suggestedDefault = undefined;
  }
}

/**
 * Step 5 (service_account mode): walks three Google ADC checkpoints
 * with a re-check-or-skip loop at each — install gcloud, log in to
 * ADC, then pin a quota project. The user controls the pace; any
 * step can be skipped and verified later with `npm run doctor`.
 * Mutually exclusive with the user_oauth-mode `promptGoogleOAuth`
 * above.
 */
async function walkAdcSetup() {
  banner("Step 5 · Google ADC", "Service account mode uses your gcloud ADC credentials.");
  const gcloudOk = await ensureGcloudInstalled();
  if (!gcloudOk) return;
  const loggedIn = await ensureAdcLogin();
  if (!loggedIn) return;
  await ensureQuotaProject();
}

/**
 * Step 6: MCP server URL. The localhost default is opaque without
 * context — this step explains that the MCP server is a separate
 * process (the published `@google/chrome-enterprise-premium-mcp`
 * package, or a local clone if you're hacking on it) before asking
 * the URL question. A custom-URL escape hatch covers remote
 * deployments.
 */
async function chooseMcpUrl(current: string | undefined): Promise<string> {
  banner(
    "Step 6 · MCP server",
    "The CEP admin tools live in a separate process. Pocket CEP talks to it over HTTP.",
  );

  console.log(
    `${DIM}Most contributors use the official npm package. \`npm run dev:full\`${RESET}`,
  );
  console.log(
    `${DIM}launches it alongside Next on port 4000:${RESET}\n`,
  );
  console.log(`  ${CYAN}npx @google/chrome-enterprise-premium-mcp@latest${RESET}\n`);
  console.log(
    `${DIM}If you've cloned the MCP source locally and want to run that${RESET}`,
  );
  console.log(
    `${DIM}instead, override the command when starting dev:${RESET}\n`,
  );
  console.log(`  ${CYAN}MCP_SERVER_CMD="node /path/to/cmcp/mcp-server.js" npm run dev:full${RESET}\n`);
  console.log(
    `${DIM}Either way, Pocket CEP still dials ${DEFAULT_MCP_URL} — the URL doesn't${RESET}`,
  );
  console.log(`${DIM}change; only what's on the other end does.${RESET}\n`);

  const isCustom = current !== undefined && current !== "" && current !== DEFAULT_MCP_URL;

  const choice = await select<"local" | "custom">({
    message: "Which URL should Pocket CEP dial?",
    default: isCustom ? "custom" : "local",
    choices: [
      {
        name: `${DEFAULT_MCP_URL} — local, started by \`npm run dev:full\``,
        value: "local",
        description: "Covers both the npm package and a local source clone (via MCP_SERVER_CMD).",
      },
      {
        name: "Somewhere else — I have an MCP server running remotely",
        value: "custom",
        description: "Enter a URL (staging deployment, Cloud Run, shared demo, etc.).",
      },
    ],
  });

  if (choice === "local") {
    note(`Set to ${DEFAULT_MCP_URL}. Start the server with \`npm run dev:full\` when ready.`);
    return DEFAULT_MCP_URL;
  }

  return input({
    message: "MCP_SERVER_URL:",
    default: isCustom ? current : DEFAULT_MCP_URL,
    validate: async (value) => {
      const url = value.trim();
      if (!url) return "URL is required";
      try {
        new URL(url);
      } catch {
        return "Not a valid URL";
      }
      const result = await probeMcpServer(url);
      if (result.ok) return true;
      return `${result.message}. Skip the reachability check with Ctrl+C if the server isn't running yet.`;
    },
  });
}

async function optionalModelOverride(
  provider: "claude" | "gemini",
  current: string | undefined,
): Promise<string> {
  const wantOverride = await confirm({
    message: `Use the default ${provider} model? (No lets you pin a specific model ID.)`,
    default: current ? false : true,
  });
  if (wantOverride) return "";
  return input({
    message: `LLM_MODEL for ${provider}:`,
    default: current,
    validate: (v) => (v.trim().length > 0 ? true : "Leave blank to use the default"),
  });
}

async function main() {
  console.log(`${BOLD}\nPocket CEP — Interactive Setup${RESET}`);
  console.log(`${DIM}Writes .env.local (existing values are used as defaults).${RESET}`);

  const existing = readExistingEnv();

  const authMode = await chooseAuthMode(existing.AUTH_MODE);
  const authSecret = await chooseAuthSecret(existing.BETTER_AUTH_SECRET);
  const llmProvider = await chooseLlmProvider(existing);

  const apiKey =
    llmProvider === "claude"
      ? await promptAnthropicKey(existing.ANTHROPIC_API_KEY)
      : await promptGeminiKey(existing.GOOGLE_AI_API_KEY);

  note(
    "Tip: the in-app model picker (top bar) lets you paste keys for any\n" +
      "provider — Claude, Gemini, OpenAI — for casual use. Keys live in your\n" +
      "browser's localStorage only. No need to re-run setup.",
  );

  let clientId = "";
  let clientSecret = "";
  if (authMode === "user_oauth") {
    const creds = await promptGoogleOAuth(existing);
    clientId = creds.clientId;
    clientSecret = creds.clientSecret;
  } else {
    await walkAdcSetup();
  }

  const mcpUrl = await chooseMcpUrl(existing.MCP_SERVER_URL);
  const modelOverride = await optionalModelOverride(llmProvider, existing.LLM_MODEL);

  const merged: EnvMap = {
    ...existing,
    AUTH_MODE: authMode,
    LLM_PROVIDER: llmProvider,
    BETTER_AUTH_SECRET: authSecret,
    MCP_SERVER_URL: mcpUrl,
    LLM_MODEL: modelOverride,
  };

  // Only set the chosen provider's key; leave any previously-set keys
  // for the other provider(s) intact. The Zod schema discriminates on
  // LLM_PROVIDER and only requires the matching key — extras are
  // allowed, and the in-app model picker can use them as BYOK.
  if (llmProvider === "claude") {
    merged.ANTHROPIC_API_KEY = apiKey;
  } else {
    merged.GOOGLE_AI_API_KEY = apiKey;
  }

  if (authMode === "user_oauth") {
    merged.GOOGLE_CLIENT_ID = clientId;
    merged.GOOGLE_CLIENT_SECRET = clientSecret;
  }

  banner("Review", "Nothing is written until you confirm.");
  console.log(`  AUTH_MODE     ${CYAN}${authMode}${RESET}`);
  console.log(`  LLM_PROVIDER  ${CYAN}${llmProvider}${RESET}`);
  console.log(
    `  LLM_MODEL     ${CYAN}${modelOverride || `(default for ${llmProvider})`}${RESET}`,
  );
  console.log(`  MCP_SERVER_URL ${CYAN}${mcpUrl}${RESET}`);
  console.log(`  Secrets       ${DIM}masked, written to .env.local${RESET}`);

  const write = await confirm({ message: `Write ${ENV_PATH}?`, default: true });
  if (!write) {
    console.log(`${YELLOW}Aborted. No files changed.${RESET}\n`);
    return;
  }

  writeEnv(merged);
  console.log(`  ${GREEN}✓${RESET} Wrote ${ENV_PATH}\n`);

  const runDoctor = await confirm({ message: "Run `npm run doctor` now?", default: true });
  if (runDoctor) {
    console.log();
    spawnSync("npm", ["run", "doctor"], { stdio: "inherit" });
  } else {
    console.log(`${DIM}You can run it any time with: npm run doctor${RESET}\n`);
  }
}

main().catch((error: unknown) => {
  if (error instanceof Error && error.name === "ExitPromptError") {
    console.log(`\n${YELLOW}Setup cancelled.${RESET}\n`);
    process.exit(0);
  }
  console.error("\nSetup failed:", error);
  process.exit(1);
});
