/**
 * @file Interactive setup CLI for Pocket CEP.
 *
 * Run with: npm run setup
 *
 * Guides a new developer through the .env.local configuration with live
 * validation at every step. Prompts are mode-aware (user_oauth asks for
 * Google OAuth creds; service_account walks through ADC) and API keys
 * are probed against the real upstream service before the script moves
 * on — so "setup finishes clean" is a real guarantee, not a vibe.
 *
 * Safe to re-run: existing .env.local values are loaded as defaults and
 * any keys we don't recognise are preserved unchanged on write.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { randomBytes } from "node:crypto";
import { select, input, password, confirm } from "@inquirer/prompts";
import { spawnSync } from "node:child_process";

import {
  probeAdcToken,
  probeAnthropicKey,
  probeGeminiKey,
  probeMcpServer,
} from "../src/lib/doctor-checks";

const ENV_PATH = resolve(process.cwd(), ".env.local");

const DIM = "\x1b[2m";
const BOLD = "\x1b[1m";
const CYAN = "\x1b[36m";
const GREEN = "\x1b[32m";
const YELLOW = "\x1b[33m";
const RESET = "\x1b[0m";

type EnvMap = Record<string, string>;

/**
 * Parses an existing .env.local into a map so we can preserve unknown
 * keys and pre-fill known ones as prompt defaults. Mirrors the trivial
 * parser used by doctor.ts — no quoting, no variable expansion.
 */
function readExistingEnv(): EnvMap {
  if (!existsSync(ENV_PATH)) return {};
  const content = readFileSync(ENV_PATH, "utf-8");
  const env: EnvMap = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim();
    env[key] = value;
  }
  return env;
}

/**
 * Writes the env map back to disk as a predictable, human-editable file:
 * a header, then `KEY=value` lines grouped by section. Any keys in the
 * map we don't have a category for land under "Other" so re-running
 * setup never drops user additions on the floor.
 */
function writeEnv(env: EnvMap): void {
  const ordered: Array<[string, string[]]> = [
    ["Secrets", ["BETTER_AUTH_SECRET", "ANTHROPIC_API_KEY", "GOOGLE_AI_API_KEY"]],
    ["Google OAuth (user_oauth mode only)", ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"]],
    ["Mode", ["AUTH_MODE", "LLM_PROVIDER", "LLM_MODEL"]],
    ["URLs", ["BETTER_AUTH_URL", "MCP_SERVER_URL"]],
  ];

  const seen = new Set<string>();
  const lines: string[] = [
    "# Generated by `npm run setup` — re-running setup preserves values you set",
    "# and adds only the keys you configure. Hand-edits are safe.",
    "",
  ];

  for (const [section, keys] of ordered) {
    const present = keys.filter((k) => env[k] !== undefined && env[k] !== "");
    if (present.length === 0) continue;
    lines.push(`# ${section}`);
    for (const key of present) {
      lines.push(`${key}=${env[key]}`);
      seen.add(key);
    }
    lines.push("");
  }

  const unknown = Object.keys(env).filter((k) => !seen.has(k) && env[k] !== "");
  if (unknown.length > 0) {
    lines.push("# Other");
    for (const key of unknown) {
      lines.push(`${key}=${env[key]}`);
    }
    lines.push("");
  }

  writeFileSync(ENV_PATH, lines.join("\n"), { mode: 0o600 });
}

function banner(title: string, subtitle?: string) {
  console.log(`\n${BOLD}${title}${RESET}`);
  if (subtitle) console.log(`${DIM}${subtitle}${RESET}`);
}

function note(text: string) {
  console.log(`${DIM}${text}${RESET}`);
}

function checking(msg: string) {
  process.stdout.write(`  ${YELLOW}…${RESET} ${msg}…`);
}

function okClear(msg: string) {
  process.stdout.write(`\r  ${GREEN}✓${RESET} ${msg}${" ".repeat(20)}\n`);
}

function failClear(msg: string) {
  process.stdout.write(`\r  \x1b[31m✗${RESET} ${msg}${" ".repeat(20)}\n`);
}

/**
 * Wraps an inquirer `validate` callback that calls an upstream API so
 * the prompt's own red-text error line does the heavy lifting. Returns
 * `true` on success, an error string on failure (inquirer's contract).
 */
async function validateWithProbe(
  probe: () => Promise<{ ok: boolean; message: string }>,
  successMessage: string,
): Promise<true | string> {
  const result = await probe();
  return result.ok ? true : `${successMessage.replace("accepted", "rejected")} — ${result.message}`;
}

/**
 * Step 1: auth mode. We explain both flavors inline and use the
 * existing .env.local value as the default if re-running setup.
 */
async function chooseAuthMode(current: string | undefined) {
  banner("Step 1 · Authentication mode", "How does Pocket CEP talk to Google APIs?");
  return select<"service_account" | "user_oauth">({
    message: "Which auth mode?",
    default: current === "user_oauth" ? "user_oauth" : "service_account",
    choices: [
      {
        name: "service_account · ADC (recommended for local demos)",
        value: "service_account",
        description: "Uses `gcloud auth application-default login`. No user sign-in; shared identity.",
      },
      {
        name: "user_oauth · Google OAuth (per-user attribution)",
        value: "user_oauth",
        description: "Users sign in with Google. Their token is forwarded to the MCP server.",
      },
    ],
  });
}

/**
 * Step 2: LLM provider. Validation happens on the API-key step
 * downstream — we only pick the provider here.
 */
async function chooseLlmProvider(current: string | undefined) {
  banner("Step 2 · LLM provider", "Which model powers the chat agent?");
  return select<"claude" | "gemini">({
    message: "Which provider?",
    default: current === "gemini" ? "gemini" : "claude",
    choices: [
      {
        name: "claude · Anthropic Claude (via @ai-sdk/anthropic)",
        value: "claude",
        description: "Requires an ANTHROPIC_API_KEY from https://console.anthropic.com/",
      },
      {
        name: "gemini · Google Generative AI (via @ai-sdk/google)",
        value: "gemini",
        description: "Requires a GOOGLE_AI_API_KEY from https://aistudio.google.com/apikey",
      },
    ],
  });
}

/**
 * Step 3: BETTER_AUTH_SECRET. If the current value looks unsafe
 * (missing or the placeholder from .env.local.example), we offer
 * to generate a fresh one. Otherwise we leave it untouched.
 */
async function chooseAuthSecret(current: string | undefined): Promise<string> {
  banner("Step 3 · BetterAuth signing secret", "Signs the session cookie. Treat it like a password.");

  const placeholder = "please-change-me-to-a-real-secret";
  const hasReal = current && current !== placeholder && current.length >= 32;

  if (hasReal) {
    const keep = await confirm({
      message: "An existing BETTER_AUTH_SECRET looks valid. Keep it?",
      default: true,
    });
    if (keep) return current;
  }

  const generate = await confirm({
    message: "Generate a cryptographically random 32-byte secret now?",
    default: true,
  });

  if (generate) {
    const secret = randomBytes(32).toString("base64");
    console.log(`  ${GREEN}✓${RESET} Generated a new 32-byte secret.`);
    return secret;
  }

  return password({
    message: "Paste your own BETTER_AUTH_SECRET:",
    mask: "•",
    validate: (v) => (v.trim().length >= 16 ? true : "Use at least 16 characters"),
  });
}

/**
 * If an existing key is present, probe it first and offer to keep it
 * so we don't ask the user to re-paste a working secret. Returns the
 * kept value or `null` to signal "prompt for a new one".
 */
async function tryKeepExistingKey(
  label: string,
  current: string | undefined,
  probe: (value: string) => Promise<{ ok: boolean; message: string }>,
): Promise<string | null> {
  if (!current) return null;
  checking(`Probing existing ${label}`);
  const result = await probe(current);
  if (!result.ok) {
    failClear(`Existing ${label} was rejected — you'll need to paste a new one`);
    return null;
  }
  okClear(`Existing ${label} is valid`);
  const keep = await confirm({ message: `Keep the existing ${label}?`, default: true });
  return keep ? current : null;
}

/**
 * Step 4a: Anthropic key — masked input, validated by the same
 * /v1/messages probe doctor uses. If the key is wrong we re-prompt;
 * we never move on with a bad key.
 */
async function promptAnthropicKey(current: string | undefined) {
  banner(
    "Step 4 · ANTHROPIC_API_KEY",
    "We'll probe https://api.anthropic.com/v1/messages to confirm it works.",
  );
  note("Get one at https://console.anthropic.com/ → Settings → API Keys");

  const kept = await tryKeepExistingKey("Anthropic key", current, probeAnthropicKey);
  if (kept) return kept;

  return password({
    message: "Paste your Anthropic API key:",
    mask: "•",
    validate: async (value) => {
      const trimmed = value.trim();
      if (!trimmed) return "Key is required";
      if (!trimmed.startsWith("sk-ant-")) {
        return "Anthropic keys start with `sk-ant-` — double-check the value";
      }
      return validateWithProbe(() => probeAnthropicKey(trimmed), "Key accepted");
    },
  });
}

/**
 * Step 4b: Google AI key — validated by listing models on
 * generativelanguage.googleapis.com.
 */
async function promptGeminiKey(current: string | undefined) {
  banner(
    "Step 4 · GOOGLE_AI_API_KEY",
    "We'll probe generativelanguage.googleapis.com/v1beta/models to confirm it works.",
  );
  note("Get one at https://aistudio.google.com/apikey");

  const kept = await tryKeepExistingKey("Google AI key", current, probeGeminiKey);
  if (kept) return kept;

  return password({
    message: "Paste your Google AI API key:",
    mask: "•",
    validate: async (value) => {
      const trimmed = value.trim();
      if (!trimmed) return "Key is required";
      return validateWithProbe(() => probeGeminiKey(trimmed), "Key accepted");
    },
  });
}

const GOOGLE_CLIENT_ID_RE = /^\d+-\w+\.apps\.googleusercontent\.com$/;

/**
 * Step 5: Google OAuth client credentials. Only runs in user_oauth
 * mode. The client ID format is strict, so we validate it with the
 * same regex the Zod env schema uses — catch paste errors here rather
 * than as a cryptic OAuth error at runtime.
 */
async function promptGoogleOAuth(current: EnvMap) {
  banner(
    "Step 5 · Google OAuth client",
    "console.cloud.google.com → APIs & Services → Credentials",
  );
  note(
    "Add this redirect URI to your OAuth client:\n   http://localhost:3000/api/auth/callback/google",
  );

  const clientId = await input({
    message: "GOOGLE_CLIENT_ID:",
    default: current.GOOGLE_CLIENT_ID || undefined,
    validate: (v) => {
      const trimmed = v.trim();
      if (!trimmed) return "Client ID is required";
      return GOOGLE_CLIENT_ID_RE.test(trimmed)
        ? true
        : "Expected format: 123456789-abc.apps.googleusercontent.com";
    },
  });

  const clientSecret = await password({
    message: "GOOGLE_CLIENT_SECRET:",
    mask: "•",
    validate: (v) => (v.trim().length > 0 ? true : "Client secret is required"),
  });

  return { clientId: clientId.trim(), clientSecret: clientSecret.trim() };
}

/**
 * Returns true if the `gcloud` CLI is on PATH. ADC depends on it, so we
 * preflight before the ADC probe to give a clearer error when it's
 * missing entirely (the probe's "no credentials" message is confusing
 * if the real cause is "gcloud isn't installed yet").
 */
function isGcloudInstalled(): boolean {
  return spawnSync("gcloud", ["--version"], { stdio: "ignore" }).status === 0;
}

/**
 * Prints platform-appropriate gcloud install hints. Extracted so both
 * the "not installed" branch and the "still not installed after
 * re-check" branch render the same guidance.
 */
function printGcloudInstallHints(): void {
  console.log(`${DIM}The Google Cloud CLI is required for service-account mode —${RESET}`);
  console.log(`${DIM}Pocket CEP uses your Application Default Credentials.${RESET}`);
  console.log(`${DIM}Install it in another terminal, then come back:${RESET}\n`);

  if (process.platform === "darwin") {
    console.log(`  ${CYAN}brew install --cask google-cloud-sdk${RESET}`);
    console.log(`  ${DIM}or see https://cloud.google.com/sdk/docs/install-sdk${RESET}`);
  } else if (process.platform === "linux") {
    console.log(`  ${CYAN}https://cloud.google.com/sdk/docs/install-sdk#linux${RESET}`);
  } else if (process.platform === "win32") {
    console.log(`  ${CYAN}https://cloud.google.com/sdk/docs/install-sdk#windows${RESET}`);
  } else {
    console.log(`  ${CYAN}https://cloud.google.com/sdk/docs/install-sdk${RESET}`);
  }
  console.log();
  console.log(`${DIM}Tip: open a new shell after installing so PATH updates take effect.${RESET}\n`);
}

/**
 * Loops on "re-check or skip" until gcloud is installed or the user
 * chooses to defer. Returns true when gcloud is ready, false when the
 * user opted to skip ADC entirely.
 */
async function ensureGcloudInstalled(): Promise<boolean> {
  checking("Checking for `gcloud`");
  if (isGcloudInstalled()) {
    okClear("`gcloud` is installed");
    return true;
  }
  failClear("`gcloud` is not installed");

  for (;;) {
    printGcloudInstallHints();
    const next = await select<"recheck" | "skip">({
      message: "When you're ready:",
      default: "recheck",
      choices: [
        {
          name: "I've installed gcloud — re-check now",
          value: "recheck",
          description: "Verifies `gcloud --version` succeeds, then continues with ADC.",
        },
        {
          name: "Skip ADC for now",
          value: "skip",
          description: "Finish writing .env.local; run `npm run doctor` to verify later.",
        },
      ],
    });

    if (next === "skip") {
      note("Skipping ADC. After installing gcloud, run:");
      console.log(`  ${CYAN}gcloud auth application-default login${RESET}`);
      console.log(`  ${CYAN}npm run doctor${RESET}\n`);
      return false;
    }

    if (isGcloudInstalled()) {
      console.log(`  ${GREEN}✓${RESET} \`gcloud\` is installed\n`);
      return true;
    }
    console.log(`  \x1b[31m✗${RESET} Still not found. Open a new shell to refresh PATH.\n`);
  }
}

/**
 * Loops on "re-check or skip" until the ADC token exchange succeeds
 * or the user opts out. Assumes gcloud is already installed.
 */
async function ensureAdcLogin(): Promise<void> {
  for (;;) {
    checking("Checking Google ADC");
    const result = await probeAdcToken();
    if (result.ok) {
      okClear("ADC is configured and working");
      return;
    }
    failClear(`ADC not ready — ${result.message}`);

    console.log(`${DIM}Pocket CEP needs a Workspace admin's ADC to call the${RESET}`);
    console.log(`${DIM}Admin SDK + Admin Reports API. Run these in another terminal:${RESET}\n`);
    console.log(
      `  ${CYAN}gcloud auth application-default login \\${RESET}\n` +
        `  ${CYAN}  --scopes="https://www.googleapis.com/auth/admin.reports.audit.readonly,https://www.googleapis.com/auth/admin.directory.orgunit.readonly,https://www.googleapis.com/auth/cloud-platform"${RESET}`,
    );
    console.log(
      `  ${CYAN}gcloud auth application-default set-quota-project YOUR_PROJECT_ID${RESET}\n`,
    );

    const next = await select<"recheck" | "skip">({
      message: "When you're ready:",
      default: "recheck",
      choices: [
        {
          name: "I've logged in — re-check now",
          value: "recheck",
          description: "Verifies the token exchange succeeds.",
        },
        {
          name: "Skip for now",
          value: "skip",
          description: "`npm run doctor` will verify once you've logged in.",
        },
      ],
    });

    if (next === "skip") {
      note("Skipping ADC check. Run `npm run doctor` after logging in to verify.");
      return;
    }
  }
}

/**
 * Step 5: in service_account mode we need Google ADC. Walks through
 * both the "install gcloud" and "log in" checkpoints with a
 * re-check-or-skip loop at each step so the user controls the pace.
 */
async function walkAdcSetup() {
  banner("Step 5 · Google ADC", "Service account mode uses your gcloud ADC credentials.");
  const gcloudOk = await ensureGcloudInstalled();
  if (!gcloudOk) return;
  await ensureAdcLogin();
}

const DEFAULT_MCP_URL = "http://localhost:4000/mcp";

/**
 * Step 6: MCP server URL. Offers the recommended local path (Pocket
 * CEP starts the official `@google/chrome-enterprise-premium-mcp`
 * npx package via `npm run dev:full`) and a custom-URL escape hatch
 * for users who run their own MCP deployment.
 */
async function chooseMcpUrl(current: string | undefined): Promise<string> {
  banner("Step 6 · MCP server", "Where is the Chrome Enterprise Premium MCP server running?");

  const isCustom = current !== undefined && current !== "" && current !== DEFAULT_MCP_URL;

  const choice = await select<"local" | "custom">({
    message: "How should the MCP server run?",
    default: isCustom ? "custom" : "local",
    choices: [
      {
        name: "Let Pocket CEP launch it for you (recommended)",
        value: "local",
        description:
          "`npm run dev:full` starts `npx @google/chrome-enterprise-premium-mcp` on :4000.",
      },
      {
        name: "Point at an already-running MCP server",
        value: "custom",
        description: "I run the MCP server myself — ask me for the URL.",
      },
    ],
  });

  if (choice === "local") {
    note(`Using ${DEFAULT_MCP_URL}. Start it later with \`npm run dev:full\`.`);
    return DEFAULT_MCP_URL;
  }

  return input({
    message: "MCP_SERVER_URL:",
    default: isCustom ? current : DEFAULT_MCP_URL,
    validate: async (value) => {
      const url = value.trim();
      if (!url) return "URL is required";
      try {
        new URL(url);
      } catch {
        return "Not a valid URL";
      }
      const result = await probeMcpServer(url);
      if (result.ok) return true;
      return `${result.message}. Skip the reachability check with Ctrl+C if the server isn't running yet.`;
    },
  });
}

async function optionalModelOverride(
  provider: "claude" | "gemini",
  current: string | undefined,
): Promise<string> {
  const wantOverride = await confirm({
    message: `Use the default ${provider} model? (No lets you pin a specific model ID.)`,
    default: current ? false : true,
  });
  if (wantOverride) return "";
  return input({
    message: `LLM_MODEL for ${provider}:`,
    default: current,
    validate: (v) => (v.trim().length > 0 ? true : "Leave blank to use the default"),
  });
}

async function main() {
  console.log(`${BOLD}\nPocket CEP — Interactive Setup${RESET}`);
  console.log(`${DIM}Writes .env.local (existing values are used as defaults).${RESET}`);

  const existing = readExistingEnv();

  const authMode = await chooseAuthMode(existing.AUTH_MODE);
  const llmProvider = await chooseLlmProvider(existing.LLM_PROVIDER);
  const authSecret = await chooseAuthSecret(existing.BETTER_AUTH_SECRET);

  const apiKey =
    llmProvider === "claude"
      ? await promptAnthropicKey(existing.ANTHROPIC_API_KEY)
      : await promptGeminiKey(existing.GOOGLE_AI_API_KEY);

  let clientId = "";
  let clientSecret = "";
  if (authMode === "user_oauth") {
    const creds = await promptGoogleOAuth(existing);
    clientId = creds.clientId;
    clientSecret = creds.clientSecret;
  } else {
    await walkAdcSetup();
  }

  const mcpUrl = await chooseMcpUrl(existing.MCP_SERVER_URL);
  const modelOverride = await optionalModelOverride(llmProvider, existing.LLM_MODEL);

  const merged: EnvMap = {
    ...existing,
    AUTH_MODE: authMode,
    LLM_PROVIDER: llmProvider,
    BETTER_AUTH_SECRET: authSecret,
    MCP_SERVER_URL: mcpUrl,
    LLM_MODEL: modelOverride,
  };

  if (llmProvider === "claude") {
    merged.ANTHROPIC_API_KEY = apiKey;
    merged.GOOGLE_AI_API_KEY = "";
  } else {
    merged.GOOGLE_AI_API_KEY = apiKey;
    merged.ANTHROPIC_API_KEY = "";
  }

  if (authMode === "user_oauth") {
    merged.GOOGLE_CLIENT_ID = clientId;
    merged.GOOGLE_CLIENT_SECRET = clientSecret;
  }

  banner("Review", "Nothing is written until you confirm.");
  console.log(`  AUTH_MODE     ${CYAN}${authMode}${RESET}`);
  console.log(`  LLM_PROVIDER  ${CYAN}${llmProvider}${RESET}`);
  console.log(
    `  LLM_MODEL     ${CYAN}${modelOverride || `(default for ${llmProvider})`}${RESET}`,
  );
  console.log(`  MCP_SERVER_URL ${CYAN}${mcpUrl}${RESET}`);
  console.log(`  Secrets       ${DIM}masked, written to .env.local${RESET}`);

  const write = await confirm({ message: `Write ${ENV_PATH}?`, default: true });
  if (!write) {
    console.log(`${YELLOW}Aborted. No files changed.${RESET}\n`);
    return;
  }

  writeEnv(merged);
  console.log(`  ${GREEN}✓${RESET} Wrote ${ENV_PATH}\n`);

  const runDoctor = await confirm({ message: "Run `npm run doctor` now?", default: true });
  if (runDoctor) {
    console.log();
    spawnSync("npm", ["run", "doctor"], { stdio: "inherit" });
  } else {
    console.log(`${DIM}You can run it any time with: npm run doctor${RESET}\n`);
  }
}

main().catch((error: unknown) => {
  if (error instanceof Error && error.name === "ExitPromptError") {
    console.log(`\n${YELLOW}Setup cancelled.${RESET}\n`);
    process.exit(0);
  }
  console.error("\nSetup failed:", error);
  process.exit(1);
});
